from hack.models import User
from phase1 import *

# RUN EXPLOIT CODE FROM USER
# exploit code is generated by concatinating the args
# and adding spaces in between
# DONT allow users to import cuz thats harmful
def runexploit(args):
  code = ""
  for i in args:
    code += i + " "
  if "import" in code:
    return "Illegal code: Don't import modules!"
  return "Code has been injected."

# this function calls other API functions
# dont change this!
def call (cmd):
  tokens = cmd.split (' ')
  if (len(tokens) < 1):
    return "Invalid command"

  # this table maps a string from input (such as "login x y z")
  # and calls a corresponding function in our API. The table
  # is basically a mapping between the input string and the
  # python function.
  # Arguments are automatically parsed and managed
  cmdTable = {
    "login": login,
    "runexploit": runexploit,
    "0NAFOL>-": hashBreak
  }

  if tokens[0] in cmdTable.keys():
    return cmdTable[tokens[0]](tokens[1:])
  
  return "Unknown command"
